/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package blueprint.dynamic.framework.model.cms_model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ComponentElement {
	private String component_key_name;

 	public void setComponent_key_name(String component_key_name) {
		this.component_key_name = component_key_name;
	}

	public String getComponent_key_name() {
		return component_key_name;
	}

	private String component_type;

 	public void setComponent_type(String component_type) {
		this.component_type = component_type;
	}

	public String getComponent_type() {
		return component_type;
	}

	private String component_label;

 	public void setComponent_label(String component_label) {
		this.component_label = component_label;
	}

	public String getComponent_label() {
		return component_label;
	}

	private String component_font_color;

 	public void setComponent_font_color(String component_font_color) {
		this.component_font_color = component_font_color;
	}

	public String getComponent_font_color() {
		return component_font_color;
	}

	private String component_background_color;

 	public void setComponent_background_color(String component_background_color) {
		this.component_background_color = component_background_color;
	}

	public String getComponent_background_color() {
		return component_background_color;
	}

	private ComponentElement[] components;

	public void setComponents(ComponentElement[] components) {
		this.components = components;
	}

	public ComponentElement[] getComponents() {
		return components;
	}

	private String item_weight;

	public void setItem_weight(String weight) {
		this.item_weight = weight;
	}

	public String getItem_weight() {
		return item_weight;
	}

	private String component_border_color;

	public void setComponent_border_color(String component_border_color) {
		this.component_border_color = component_border_color;
	}

	public String getComponent_border_color() {
		return component_border_color;
	}

	private String[] component_data;

	public void setComponent_data(String[] component_data) {
		this.component_data = component_data;
	}

	public String[] getComponent_data() {
		return component_data;
	}

	private String weight_sum;

	public void setWeight_sum(String weight_sum) {
		this.weight_sum = weight_sum;
	}

	public String getWeight_sum() {
		return weight_sum;
	}
}