/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package blueprint.dynamic.framework.model.cms_model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ContainerElement {
	private String container_background_color;

 	public void setContainer_background_color(String container_background_color) {
		this.container_background_color = container_background_color;
	}

	public String getContainer_background_color() {
		return container_background_color;
	}

	private ComponentElement[] components;

 	public void setComponents(ComponentElement[] components) {
		this.components = components;
	}

	public ComponentElement[] getComponents() {
		return components;
	}

	private ContainerElement[] container;

 	public void setContainer(ContainerElement[] container) {
		this.container = container;
	}

	public ContainerElement[] getContainer() {
		return container;
	}

	private String container_name;

 	public void setContainer_name(String container_name) {
		this.container_name = container_name;
	}

	public String getContainer_name() {
		return container_name;
	}

	private String item_orientation;

 	public void setItem_orientation(String orientation) {
		this.item_orientation = orientation;
	}

	public String getItem_orientation() {
		return item_orientation;
	}

	private String item_weight;

 	public void setItem_weight(String weight) {
		this.item_weight = weight;
	}

	public String getItem_weight() {
		return item_weight;
	}

	private String weight_sum;

	public void setWeight_sum(String weight_sum) {
		this.weight_sum = weight_sum;
	}

	public String getWeight_sum() {
		return weight_sum;
	}

	private String item_id;

	public void setItem_id(String item_id) {
		this.item_id = item_id;
	}

	public String getItem_id() {
		return item_id;
	}

	private String container_type;

	public void setContainer_type(String container_type) {
		this.container_type = container_type;
	}

	public String getContainer_type() {
		return container_type;
	}
}