/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package blueprint.dynamic.framework.model.cms_model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class RootCms {
	private Application application;

	private String logger;

	private String grid;

	public Application getApplication ()
	{
		return application;
	}

	public void setApplication (Application application)
	{
		this.application = application;
	}

	public String getLogger ()
	{
		return logger;
	}

	public void setLogger (String logger)
	{
		this.logger = logger;
	}

	public String getGrid ()
	{
		return grid;
	}

	public void setGrid (String grid)
	{
		this.grid = grid;
	}

	@Override
	public String toString()
	{
		return "ClassPojo [application = "+application+", logger = "+logger+", grid = "+grid+"]";
	}
}