/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package blueprint.dynamic.framework.model.cms_model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class RootCms {
	private ApiElement[] apis;

	public void setApis(ApiElement[] apis) {
		this.apis = apis;
	}

	public ApiElement[] getApis() {
		return apis;
	}

	private java.lang.Object[] keys;

	public void setKeys(java.lang.Object[] keys) {
		this.keys = keys;
	}

	public java.lang.Object[] getKeys() {
		return keys;
	}

	private Database_tablElement[] database_tables;

	public void setDatabase_tables(Database_tablElement[] database_tables) {
		this.database_tables = database_tables;
	}

	public Database_tablElement[] getDatabase_tables() {
		return database_tables;
	}

	private java.lang.Object[] status_messages;

	public void setStatus_messages(java.lang.Object[] status_messages) {
		this.status_messages = status_messages;
	}

	public java.lang.Object[] getStatus_messages() {
		return status_messages;
	}

	private ScreenElement[] screens;

	public void setScreens(ScreenElement[] screens) {
		this.screens = screens;
	}

	public ScreenElement[] getScreens() {
		return screens;
	}

	private java.lang.Object[] data_status_code;

	public void setData_status_code(java.lang.Object[] data_status_code) {
		this.data_status_code = data_status_code;
	}

	public java.lang.Object[] getData_status_code() {
		return data_status_code;
	}

}