/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package blueprint.dynamic.framework.model.cms_model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ScreenElement {
	private ContainerElement[] container;

 	public void setContainer(ContainerElement[] container) {
		this.container = container;
	}

	public ContainerElement[] getContainer() {
		return container;
	}

	private String item_orientation;

 	public void setItem_orientation(String orientation) {
		this.item_orientation = orientation;
	}

	public String getItem_orientation() {
		return item_orientation;
	}

	private String screen_type;

 	public void setScreen_type(String screen_type) {
		this.screen_type = screen_type;
	}

	public String getScreen_type() {
		return screen_type;
	}

	private String screen_id;

 	public void setScreen_id(String screen_id) {
		this.screen_id = screen_id;
	}

	public String getScreen_id() {
		return screen_id;
	}

	private String screen_display_name;

 	public void setScreen_display_name(String screen_display_name) {
		this.screen_display_name = screen_display_name;
	}

	public String getScreen_display_name() {
		return screen_display_name;
	}

	private String table_name;

 	public void setTable_name(String table_name) {
		this.table_name = table_name;
	}

	public String getTable_name() {
		return table_name;
	}

	private String weight_sum;

	public void setWeight_sum(String weight_sum) {
		this.weight_sum = weight_sum;
	}

	public String getWeight_sum() {
		return weight_sum;
	}

}